- hosts: 'webservers'
  remote_user: gayane
  vars:
      ansible_python_interpreter: python3
  tasks:
    - name: 'Install nginx'
      apt:
        name: 'nginx'
        state: 'present'
      become: true
    - name: 'Install MySQL'
      apt:
          name: 
            - 'mysql-server'
            - 'python3-pymysql'
            - 'php-mysql'
          state: 'latest'
          update_cache: true
      become: true
    - name: 'Install php fpm'
      apt:
          name: 'php-fpm'
          state: 'present'
      become: true
    - name: 'install php-mysql'
      apt:
          name: 'php-mysql'
          state: 'present'
      become: true
    - name: 'Start the MySQL service'
      become: true
      service: 
        name: mysql 
        state: started
        enabled: true
      become: true
    - name: 'Create a new database'
      mysql_db: 
        name: 'wordpress_test2' 
        login_user: wp_user
        login_password: root
      become: true
    - name: 'Download wordpress'
      get_url:
          url: 'https://wordpress.org/latest.tar.gz'
          dest: '/var/www/latest.tar.gz'
      become: true
    - name: 'create www directory'
      file:
        state: directory
        path: /var/www
        owner: root
        group: root
        mode: 0755
      become: true
    - name: 'untar wordpress'
      ansible.builtin.unarchive:
        src: '/var/www/latest.tar.gz'
        dest: '/var/www'
        remote_src: true
      become: true
    - name: 'delete wordpress tar'
      file:
        path: '/var/www/latest.tar.gz'
        state: 'absent'
      become: true
    - name: Change file ownership
      ansible.builtin.file:
        path: /var/www/wordpress
        owner: www-data
        group: www-data
      become: true
    - name: 'Rename wp file'
      command: mv '/var/www/wordpress/wp-config-sample.php' '/var/www/wordpress/wp-config.php'
      become: true
    - name: 'Set DB settings'
      lineinfile:
        dest: '/var/www/wordpress/wp-config.php'
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', 'wordpress_test2');"}
        - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', 'wp_user');"}
        - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', 'root');"}
      become: true
    - name: Set the correct permissions on Wordpress directories
      command: find /var/www/wordpress/ -type d -exec chmod 750 {} \;
    - name: Set the correct permissions for Wordpress files
      command: find /var/www/wordpress/ -type f -exec chmod 640 {} \;
    - name: Copy default to wordpress
      copy: 
        src: /etc/nginx/sites-available/default 
        dest: /etc/nginx/sites-available/wordpress 
        remote_src: true
      become: true
    - name: 'Create symlink wordpess'
      ansible.builtin.file:
        force: true
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
    - name: 'Remove default config'
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: 'Change root in wordpress config'
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-available/wordpress
        regexp: ' *root *'
        line: root /var/www/wordpress;
        firstmatch: yes
    - name: 'restart nginx'
      service: 'name=nginx state=restarted'
      become: true
